language: go
sudo: false
install: true

matrix:
  include:
    - os: linux
      go: "1.10.3"
      sudo: true
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.10.3"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
script:
  - env GO111MODULE=on make ci
