apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim2
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1100Mi
  storageClassName: glusterfs-storage
